name: Yoroi npm tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
      - name: Build prod stable Yoroi
        run: npm run prod:build
      - name: Testing flow
        run: npm run flow
      - name: Testing eslint
        run: npm run eslint
      - name: Unit testing
        run: npm run jest
